.changeset/config.json
.changeset/shy-timers-lay.md
packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
packages/plugins/typescript/react-query/tests/react-query.spec.ts

Related to https://github.com/dotansimha/graphql-code-generator/issues/8346

fix(react-query): `graphql-request@5.1.x` compat

---

.changeset/violet-jokes-repair.md
dev-test/githunt/types.react-query.ts
packages/plugins/typescript/react-query/src/fetcher-custom-mapper.ts
packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts
packages/plugins/typescript/react-query/src/fetcher-fetch.ts
packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap
packages/plugins/typescript/react-query/tests/react-query.spec.ts

PR #8497 applied a fix to an issue with infintieQueries not working for custom fetchers, but in the process broke a infiniteQueries for some of the fetchers. A hotfix for this produced a type issue for queries with no variables that is not easily solvable. See discussion [here](https://github.com/dotansimha/graphql-code-generator/pull/8567#issuecomment-1306569256).
In lieu of the ideal solution which would be to conditionally keep codegen from generating infinite query hooks for queries w/o input variables (no inputs means nothing to paginate over), the best thing to do for now is revert most of the original PR.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant …

revert PR #8497: "fixes issue #7549"

---

.changeset/reproduce-laundry-pause.md
dev-test/githunt/types.vueApollo.ts
packages/plugins/typescript/vue-apollo/src/visitor.ts
packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts

... even those with required variables, as those don't have to be passed when creating the query, but only when calling `mutate`.
When you have a GraphQL mutation with non-nullable inputs, the function created by `@graphql-codegen/typescript-vue-apollo` makes the `options` parameter required instead of defaulting to an empty object `{}`.
However, you can still manually pass `{}`, since the actual variables don't have to be set in the `useAbcMutation` function, but can also be passed in the `mutate` function:
```ts
const {mutate} = useAbcMutation({}) // should default to {}
mutate({ input: 'foo' })
```
E.g. for this mutation:
```graphql
mutation Abc($input: String!) {
updateAbc(input: $input) {
id
}
}
```
Not tested, but I think the issue is …

fix(vue-apollo): default to empty options in all mutations

---

.changeset/curvy-balloons-play.md
packages/plugins/typescript/enum-array/src/config.ts
packages/plugins/typescript/enum-array/src/index.ts
packages/plugins/typescript/enum-array/tests/enum-array.spec.ts

Allows arrays to optionally be generated `as const`.
Related #58
I have run the tests in the repo.

feat: allow arrays to be generated as const

---

.changeset/reproduce-laundry-pause.md

Fixes a typo in one of the changeset files which has been causing recent runs of the `release` workflow to fail.
https://github.com/dotansimha/graphql-code-generator-community/actions/runs/3952936440/jobs/6768627038#step:5:30
Related #45

fix: typescript-vue-apollo changeset

---

.changeset/moody-islands-smoke.md
packages/plugins/typescript/enum-array/package.json
packages/plugins/typescript/enum-array/src/config.ts
packages/plugins/typescript/enum-array/src/index.ts
packages/plugins/typescript/enum-array/tests/enum-array.spec.ts
yarn.lock

Use enum members instead of string literals when `useMembers` is true.
Also updated to support `namingConvention`, `typesPrefix`, `typesSuffix`, and `enumPrefix`.
Related https://github.com/dotansimha/graphql-code-generator/issues/7169
I have run the tests in the repo.

feat: support using enum members instead of string literals

---

.changeset/large-coins-mate.md
packages/plugins/dart/flutter-freezed/src/config/config-value.ts
packages/plugins/dart/flutter-freezed/src/config/plugin-config.ts
packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/class-block.ts
packages/plugins/dart/flutter-freezed/tests/plugin.spec.ts

added @type decorators, added missing TypeName and FieldName variables in the exampleMarkdowns
`mergeTypes` signature changed to `mergeTypes?: Record<string, TypeName[]>`

docs(plugin config): :memo: updated plugin-config

---

.changeset/perfect-seahorses-live.md
packages/plugins/dart/flutter-freezed/src/freezed-declaration-blocks/enum-block.ts
packages/plugins/dart/flutter-freezed/tests/plugin.spec.ts

Add missing trailing comma for enum values
Before
```dart
enum AssetOrder {
@JsonKey(name: 'contentType_ASC')
contentTypeAsc
@JsonKey(name: 'contentType_DESC')
contentTypeDesc
}
```
Now
```dart
enum AssetOrder {
@JsonKey(name: 'contentType_ASC')
contentTypeAsc,
@JsonKey(name: 'contentType_DESC')
contentTypeDesc,
}
```
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Related # (issue)
Adding links to sandbox or …

fix(flutter-freezed): missing comma in enums

---

.changeset/fifty-berries-chew.md
packages/plugins/typescript/rtk-query/src/visitor.ts
packages/plugins/typescript/rtk-query/tests/__snapshots__/rtk-query.spec.ts.snap

Previously I created a [PR](https://github.com/dotansimha/graphql-code-generator-community/pull/75) to allow the imported api name to be changed, however I forgot to change the actual implementation to use the new name. This PR does this:
```
import { newApiName } from '../baseApi'
...
const injectedApi = newApiName...
...
```
Related # (issue)
https://github.com/dotansimha/graphql-code-generator-community/issues/68
Updated the snapshot for the relevant test to show the updated import implementation

fix(typescript-rtk-query): update imported api to use alternate name

---

.changeset/smooth-papayas-invent.md
packages/plugins/typescript/generic-sdk/src/visitor.ts
packages/plugins/typescript/generic-sdk/tests/generic-sdk.spec.ts

Related #69
Make `typescript-generic-sdk` respect the `documentMode` `external` option by prefixing types with the value configured in `importOperationTypesFrom` as it is already documented.
Adapted the visitor of `typescript-generic-sdk`. Changes are heavily inspired by `typescript-graphql-request` visitor.
Added the following two unit tests. Copied from `typescript-graphql-request` test suite and adapted to generic-sdk.
- OS: macOS 13
- `@graphql-codegen/typescript-generic-sdk`:
- NodeJS: 16.17.1

Make typescript-generic-sdk respect importOperationTypesFrom option

---

.changeset/tender-bulldogs-burn.md
README.md
packages/plugins/typescript/nhost/jest.config.js
packages/plugins/typescript/nhost/package.json
packages/plugins/typescript/nhost/src/config.ts
packages/plugins/typescript/nhost/src/index.ts
packages/plugins/typescript/nhost/tests/__snapshots__/nhost.spec.ts.snap
packages/plugins/typescript/nhost/tests/nhost.spec.ts
yarn.lock

Typescript plugin for the [Nhost GraphQL client to come](https://github.com/nhost/nhost/pull/1587).
As some team members from The Guild already know, Nhost is about to release a client that generates GraphQL operations from a serializable object. Both this object and the GraphQL result are strongly typed from the schema generated by this plugin.
What the plugin does:
- Generate types with `graphql-codegem/typescript`, following a strict configuration. (the plugin does not require `@graphql-codegen/typescript` to be installed by the user but is use as a dependency).
- Minify the introspection object with `'@urql/introspection`
- Export the introspection object as well as all the types so they can be accessed through a default `import schema from './generated-schema'`
[Related documentation …

feat: Nhost typescript plugin

---

.changeset/little-dodos-refuse.md
.github/workflows/main.yml
dev-test/githunt/types.urql.tsx
packages/plugins/typescript/urql-graphcache/src/index.ts
packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts

In `@urql/exchange-graphcache@v5.2.0` `IntrospectionData` is no longer exported, but can be accessed via `CacheExchangeOpts`'s schema property.
https://github.com/urql-graphql/urql/issues/3027#issuecomment-1463386912
expected)
n/a
Updated existing test & snapshot.
CI
n/a

fix(graph-cache-config): correct `IntrospectionData`

---

.changeset/spotty-poems-carry.md
dev-test/githunt/types.urql.tsx
packages/plugins/typescript/urql-graphcache/src/index.ts
packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts

Related: https://github.com/dotansimha/graphql-code-generator-community/issues/337
`storage` is non-optional (based on types) in the latest offline exchange, so I changed the generated type to relay on the function signature. At first I wanted to import `OfflineExchangeOpts` from `@urql/exchange-graphcache` but 1) it's currently not exported, 2) even if it was, it wasn't available in lower versions (and this plugin supports lower versions —based on peerDeps).
expected)
reproduce. Please also list any relevant details for your …

improve GraphCacheConfig type in urql-graphcache plugin

---

.changeset/tough-olives-nail.md
packages/plugins/typescript/graphql-request/package.json
packages/plugins/typescript/graphql-request/src/visitor.ts
packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap

Updates `@graphql-codegen/typescript-graphql-request` to support graphql-request 6+.
Note that this is a breaking change.
Related #331
expected)
reproduce. Please also list any relevant details for your test configuration
- OS: MacOS 13.3.1
- NodeJS: 18

feature: support graphql-request 6+

---

jest.project.js
packages/plugins/flow/resolvers/tests/__snapshots__/flow-resolvers.spec.ts.snap
packages/plugins/typescript/msw/tests/__snapshots__/msw.spec.ts.snap
packages/plugins/typescript/nhost/tests/__snapshots__/nhost.spec.ts.snap
yarn.lock

Should unblock https://github.com/dotansimha/graphql-code-generator-community/pull/261

chore: stop printing prototype in Jest snapshots

---

.changeset/famous-islands-joke.md
packages/plugins/typescript/react-query/src/config.ts
packages/plugins/typescript/react-query/src/variables-generator.ts
packages/plugins/typescript/react-query/src/visitor.ts
packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap
packages/plugins/typescript/react-query/tests/react-query.spec.ts

Need to get the cache key when the `variables` is required, `getKey` function is not able to do so
Related #18 
reproduce. Please also list any relevant details for your test configuration
- OS: Mac OS 13.3
- NodeJS: 18.15.0
If this is a relatively large or complex change, kick off the discussion by explaining why you chose
the solution you did and what alternatives you considered, etc...

feat(react-query): exposeQueryRootKeys

---

.changeset/dull-laws-sneeze.md
packages/plugins/typescript/urql-graphcache/package.json

Resolves https://github.com/dotansimha/graphql-code-generator-community/issues/342
expected)

feat(typescript-urql-graphcache): mark @urql/exchange-graphcache v6 compatible

---

.changeset/kind-pens-argue.md
packages/plugins/typescript/vue-urql/src/visitor.ts
packages/plugins/typescript/vue-urql/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/vue-urql/tests/urql.spec.ts

Specify operation variable types explicitly in useQuery generated functions to be able to work with Urql 4.
Related #328
- OS: Linux
- `@graphql-codegen/typescript-vue-urql`:
- NodeJS: 18.14.0

Urql 4 now have more strict types for variables

---

.changeset/thirty-books-explode.md
packages/presets/near-operation-file/src/index.ts
packages/presets/near-operation-file/tests/near-operation-file.spec.ts

https://github.com/dotansimha/graphql-code-generator-community/issues/214
In 2019 https://github.com/dotansimha/graphql-code-generator/issues/2143 lead to https://github.com/dotansimha/graphql-code-generator/commit/1559ab682073477f5402d9231e0c91f6832af5cb. This resulted in typechecking being disabled for near-operation-file presets.
In 2022 https://github.com/dotansimha/graphql-code-generator/pull/8222 was created in the former presets repository but hasn't been created in this new repository, thanks to @klyve for that PR.
Since that change the ability to toggle this setting was introduced in: https://github.com/dotansimha/graphql-code-generator/pull/6825.
Running the same tests from https://github.com/dotansimha/graphql-code-generator/issues/2143 it should now be possible to remove the …

Accept skipDocumentsValidation config parameter from near-operation-file-preset

---

.changeset/hot-tools-destroy.md
packages/plugins/typescript/react-query/src/config.ts
packages/plugins/typescript/react-query/src/visitor.ts
packages/plugins/typescript/react-query/tests/react-query.spec.ts

I would like to propose a new feature to address this issue. I have described the proposed solution in detail on the following GitHub discussion: [Link to GitHub Discussion](https://github.com/dotansimha/graphql-code-generator/discussions/9521).
In summary, I suggest adding a new configuration field called `reactQueryImportFrom`. This field will allow users to specify a custom import path for react-query. For example:
```
reactQueryImportFrom = 'custom-react-query';
```
With this configuration, the import statements for `useQuery, useMutation, UseQueryOptions, and UseMutationOptions` will be updated as follows:
```
import { useQuery, useMutation, UseQueryOptions, UseMutationOptions } from 'custom-react-query';
```
This feature will provide flexibility and enable developers to centralize …

feat: [typescript-react-query] Able to import useQuery from own-path instead react-query or tanstack/react-query

---

.changeset/long-buses-pump.md
packages/plugins/typescript/urql/src/visitor.ts
packages/plugins/typescript/urql/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/urql/tests/urql.spec.ts

When generating subscription, it now checks if
variables are required and generates correct
options argument to the function.
Related #372 
I first made a yarn patch in my project to fix my issue.
In `graphql-code-generator-community` repo I added tests
to make sure it creates optional and required options if variables are required.
- OS: Linux
- "@graphql-codegen/add": "4.0.1"
- "@graphql-codegen/cli": "3.3.1"
- "@graphql-codegen/typescript": "3.0.4"
- "@graphql-codegen/typescript-operations": "3.0.0"
- "@graphql-codegen/typescript-react-apollo": "3.3.7"
- "@graphql-codegen/typescript-urql": "3.7.3"
- "@graphql-codegen/plugin-helpers": "4.2.0"
- "@graphql-codegen/typescript-resolvers": "3.2.1"
- …

fix(typescript-urql): optional options for subscription

---

.changeset/thirty-books-explode.md
packages/presets/near-operation-file/src/index.ts
packages/presets/near-operation-file/tests/near-operation-file.spec.ts

Reverts dotansimha/graphql-code-generator-community#413

fix(preset/near-operation-file): accept skipDocumentsValidat

---

.changeset/shiny-trainers-exercise.md
packages/plugins/typescript/react-query/src/config.ts

Corrects the comment documenting the react-query `legacyMode` option to reflect the actual behaviour:
- Corrects the default from `true` to `false` (the option actually defaults to false)
- Tweak wording of comment to better reflect the effect of changing the value from its default
Related #390
expected)
reproduce. Please also list any relevant details for your test configuration
- OS: MacOS
- `@graphql-codegen/typescript-react-query@4.1.0` 
- NodeJS: 18.16.0

chore: correct default value in `legacyMode` docs comment

---

packages/plugins/typescript/react-query/src/config.ts
packages/plugins/typescript/react-query/src/fetcher-graphql-request.ts
packages/plugins/typescript/react-query/src/visitor.ts
packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap
packages/plugins/typescript/react-query/tests/react-query.spec.ts

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
This PR modifies the current fetcher config to accept both string and object, and inside the object, user can specify the import path to their GraphQLClient instance. So it will make it easier to generated hooks by not passing down GraphQLClient.
expected)
reproduce. Please also list any relevant details for your test …

closes "global graphql-request client path in fetcher config"

---

.changeset/long-zebras-perform.md
packages/plugins/other/hasura-allow-list/src/config.ts
packages/plugins/other/hasura-allow-list/src/index.ts
packages/plugins/other/hasura-allow-list/tests/hasura-allow-list.spec.ts

add config to change fragments definition order.
Related #441 
I tested by new test code, and it generates allow list that define fragments in order they appear in the document when fragmentsOrder is set to document, and this allow list is compatible with some other plugins that did not work before. Default setting is global, and this works the same as before. So this is not breaking change.
- OS:macOS Ventura v13.4
- NodeJS:v19.9.0

feat(hasura-allow-list):add config to change fragments definition order

---

.changeset/nervous-apricots-dream.md
packages/plugins/typescript/rtk-query/package.json

Allows graphql-request v6 to be used in conjunction with the rtk-query generator.
Related #448
https://codesandbox.io/p/sandbox/thirsty-wu-kym2hd
- OS: MacOS
- `@graphql-codegen/...`: See [package.json](https://codesandbox.io/p/sandbox/thirsty-wu-kym2hd?file=%2Fpackage.json%3A9%2C3-16%2C5)
- NodeJS: 16

Allows versions 6.x of graphql-request to be used.

---

.changeset/tidy-trains-wait.md
packages/plugins/typescript/msw/src/visitor.ts
packages/plugins/typescript/msw/tests/__snapshots__/msw.spec.ts.snap
packages/plugins/typescript/msw/tests/msw.spec.ts

With the latest version of `msw`, the `typescript-msw` plugin generates code that doesn't compile. The generated code uses imports that are no longer available in `msw@2` (specifically `GraphQLRequest` and `GraphQLContext`).
This change makes the generated code more future proof, by typing the generated function with referencing the `typeof` for the `msw` graphql function instead of explicitly re-typing the expected `resolver`.
[See reproduction in CodeSandbox](https://codesandbox.io/p/sandbox/elastic-mclean-xn97t2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%25 …

typescript-msw: future proof types for generated mock functions

---

.changeset/rude-cameras-whisper.md
packages/plugins/typescript/graphql-request/src/visitor.ts
packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap
packages/plugins/typescript/graphql-request/tests/graphql-request.spec.ts

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Pass operation variables to wrapper function, so the wrapper function can use the variables to do conditional logic.
Related # (issue) https://github.com/dotansimha/graphql-code-generator-community/issues/511
expected)
Updated the unit tests
- OS:
- `@graphql-codegen/...`:
- NodeJS:
style guidelines of …

feat: [graphql-request] pass variables to wrapper function

---

.changeset/silent-brooms-fly.md
packages/plugins/typescript/graphql-request/src/index.ts

The `.ts` requirement seems like it's purely there to protect users. However, I'd like the file to be `.mts` so that it gets compiled into a `.mjs` file.
expected)
Applied similar patch via `patch-package`

Add .mts and .cts as allowable extensions to graphql-request

---

.changeset/fresh-cooks-learn.md
dev-test/githunt/types.urql.tsx
packages/plugins/typescript/urql-graphcache/src/config.ts
packages/plugins/typescript/urql-graphcache/src/index.ts
packages/plugins/typescript/urql-graphcache/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/urql-graphcache/tests/urql.spec.ts

In graphcache we export a cache and offline exchange, the offline exchange however needs extra settings like `storage` if this is unused then it's a bit hard for our implementor to use `cacheExchange` hence I propose adding an option for which export to use.
> this could be considered a breaking change, can also invert the option if you like
expected)

feat(graphcache): make offline exchange optional

---

.changeset/curly-brooms-hunt.md
packages/plugins/java/kotlin/src/visitor.ts
packages/plugins/java/kotlin/tests/kotlin.spec.ts

When using `typesSuffix` with kotlin plugin, the enum Names are generated in enum class, but not when referencing them.
The schema:
```graphql
enum UserRole {
ADMIN
USER
EDITOR
}
input SearchUser {
username: String
email: String
name: String
role: UserRole = USER
}
```
The generated code:
```kotlin
package kotlin
data class GraphqlSearchUserTypeInput(
val email: String? = null,
val name: String? = null,
val role: GraphqlUserRoleType? = GraphqlUserRoleType.USER,
val username: String? = null
) {
...
}
enum class GraphqlUserRoleType(val label: String) {
ADMINType("ADMIN"),
EDITORType("EDITOR"),
USERType("USER");
...
}
```
The names should be `ADMIN`, `EDITOR` and `USER`, but they are suffixed with `typesSuffix`.
This end up in invalid code, because `val role: GraphqlUserRoleType? = …

fix(kotlin): Enum names must not contain typesPrefix or typesSuffix

---

.changeset/dirty-donuts-invite.md
packages/plugins/typescript/react-query/src/config.ts
packages/plugins/typescript/react-query/src/visitor.ts
packages/plugins/typescript/react-query/tests/__snapshots__/react-query.spec.ts.snap
packages/plugins/typescript/react-query/tests/react-query.spec.ts

Fix `importOperationTypesFrom` missing prefix.
Related #493 #434 
Thanks all of you who help to test and find issue for 6.0.0!
Special thanks to @knoefel for digging into the code and @groomain for creating the test repo!

fix(react-query): importOperationTypesFrom missing prefix

---

.changeset/fuzzy-cars-stare.md
dev-test/githunt/types.vueApollo.ts
packages/plugins/typescript/vue-apollo/src/visitor.ts
packages/plugins/typescript/vue-apollo/tests/vue-apollo.spec.ts

Fixes #438.
Unit tests and integration tests were updated.
- OS: Ubuntu 22.04
- `@graphql-codegen/typescript-vue-apollo`: 4.1.0
- NodeJS: 18.18.2

fix(typescript-vue-apollo): make lazy query's variables optional

---

.changeset/hot-ravens-compare.md
packages/plugins/typescript/graphql-request/src/visitor.ts
packages/plugins/typescript/graphql-request/tests/__snapshots__/graphql-request.spec.ts.snap

In the latest version of @graphql-codegen/typescript-graphql-request, TypeScript error occured when moduleResolution is set to "nodenext" or "bundler".
In the issue https://github.com/dotansimha/graphql-code-generator-community/issues/501 various version error reported.
I tried with the latest version.
```
"@graphql-codegen/cli": "^5.0.0",
"@graphql-codegen/typescript": "^4.0.1",
"@graphql-codegen/typescript-graphql-request": "^6.1.0",
"@graphql-codegen/typescript-operations": "^4.0.1",
"graphql": "^16.8.1",
"graphql-request": "^6.1.0",
"typescript": "^5.3.3"
```
Here is my `tsconfig.json`. It is generated by `tsc --init` and I changed the module to "nodenext".
```
{
"compilerOptions": {
"target": "es2016",
"module": "nodenext",
"moduleResolution": "nodenext",
"esModuleInterop": true, …
```

fix(typescript-graphql-request): Fix typescript error

---

.changeset/loud-monkeys-yawn.md
dev-test/codegen.ts
dev-test/githunt/types.reactApollo.hooks.tsx
packages/plugins/typescript/react-apollo/src/config.ts
packages/plugins/typescript/react-apollo/src/visitor.ts
packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
Related #482  
reproduce. Please also list any relevant details for your test configuration
- OS: macOS Sonoma 14.1
- `@graphql-codegen/typescript-react-apollo@4.1.0`:
- NodeJS: 20.9.0
The solution(s) I came up with here may not be the most optimal, …

feat(typescript-react-apollo): Apollo Client `useFragment` hook

---

.changeset/happy-keys-kiss.md
packages/plugins/typescript/react-apollo/src/config.ts
packages/plugins/typescript/react-apollo/src/visitor.ts

TypeScript React Apollo's `defaultBaseOptions` object values are currently restricted to `string`:
https://github.com/dotansimha/graphql-code-generator-community/blob/0fea1a83eaf42f56ea68ed5f763fe00f2df7417a/packages/plugins/typescript/react-apollo/src/config.ts#L245
but they can be any number of data types, i.e. [`ignoreResults`](https://www.apollographql.com/docs/react/data/mutations#ignoreresults) is a `boolean`.
This loosens the type from `string` ➡️ `any`.
Related #463
1. configure an option with a non-string data type, i.e. [`ignoreResults`](https://www.apollographql.com/docs/react/data/mutations#ignoreresults):
```ts
const config = {
// ...
defaultBaseOptions: {
ignoreResults: true,
}
}
```
1. see that this passes TypeScript compilation …

fix(typescript-react-apollo): loosen defaultBaseOptions type

---

.changeset/giant-avocados-teach.md
packages/plugins/typescript/generic-sdk/src/visitor.ts
packages/plugins/typescript/generic-sdk/tests/__snapshots__/generic-sdk.spec.ts.snap

When using the default behavior (ie: config `rawRequest` as `false`), the generated code has a `E` unused variable which make TS yelling when TS options `noUnusedParameters` is `true`.
The fix is put that variable onlye when `rawRequest` is `true`.
Related https://github.com/dotansimha/graphql-code-generator-community/issues/453
This is replacement of https://github.com/dotansimha/graphql-code-generator-community/pull/454 (because OP doesn't reply)
I tried to add stuff inside `dev-test` but I failed to understand properly how can I achieve that. Happy to add them if someone point me to the right direction.
expected)
The generated code doesn't include the variable so TypeScript is happy. …

Fix unused parameter in generated code

---

.changeset/tricky-hats-push.md
dev-test/githunt/flow.flow.js
packages/plugins/flow/operations/src/flow-selection-set-processor.ts
packages/plugins/flow/operations/tests/__snapshots__/flow-documents.spec.ts.snap
packages/plugins/flow/operations/tests/flow-documents.spec.ts

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Flow-operations tries to spread exact/inexact objects into the same merged object which leads to flow errrors.
I have already been running with this change in a custom plugin for quite some time.
Related issue [#8000](https://github.com/dotansimha/graphql-code-generator-community/issues/198)
[Flow Try demonstrating the issue](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BM7c+A+Y2yU4IwRO4A6SFBIrGVDGL09ZIFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuN34N …

feat(flow): flow-operations tries to spread inexact objects #8000

---

.changeset/many-pens-talk.md
packages/plugins/java/java/src/visitor.ts
packages/plugins/java/java/tests/java.spec.ts

This fixes an issue with generated java query input arguments as enum values lacked null checks.
Related #637
https://stackblitz.com/edit/github-val3pw
Updated unit tests and tested locally that this fixes a problem in a project that I'm using this dependency for.

fix: add null validation for java enum arguments

---

.changeset/kind-pens-argue.md
packages/plugins/typescript/vue-urql/src/visitor.ts
packages/plugins/typescript/vue-urql/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/vue-urql/tests/urql.spec.ts

Generate explicit type for variables used in a subscription to work with URQL v4
This is basically the same as accepted https://github.com/dotansimha/graphql-code-generator-community/pull/329#issue-1664396694 but for subscriptions.
Otherwise it doesn't compile generated files if subscription have a required variable.
**WARNING:** This is possibly a breaking change - now it requires to define empty object for variables argument if no variables are used in subscription
Related #328
expected)
- OS: Linux
- `@graphql-codegen/typescript-vue-urql`:
- NodeJS: 18.14.0

Generate explicit type for variables used in a subscription to work with URQL v4

---

.changeset/funny-doors-attend.md
README.md
packages/plugins/typescript/enum-array/src/index.ts
packages/plugins/typescript/enum-array/tests/enum-array.spec.ts

- added support to enum-array plugin for introspection result / remote schema
- added `@graphql-codegen/typescript-enum-array` to readme list
added test cases, also running a local fork at work with the same changes

fix(enum-array): support introspection result

---

.changeset/tough-roses-divide.md
packages/plugins/typescript/named-operations-object/src/index.ts
packages/plugins/typescript/named-operations-object/tests/plugin.spec.ts

This adds an option to configure the `named-operations-object` plugin so that it throws an error when a duplicate operation definition is found.
Related #774

feat(named-operations-object): add option to throw on duplicates

---

.changeset/few-apes-march.md
packages/plugins/typescript/react-apollo/package.json

`graphql-tag` is only used in .spec files within the `typescript-react-apollo` package. Similar to `typescript-apollo-angular`, this commit moves `graphql-tag` to devDependencies so package consumers aren't required to install it to remove warning:
```
warning " > @graphql-codegen/typescript-react-apollo@4.3.0" has unmet peer dependency "graphql-tag@^2.0.0".
```
Closes https://github.com/dotansimha/graphql-code-generator-community/issues/471
expected
- Checked that dev/build environment tasks still work as expected.
- Checked local install of this updated package in another project repo to ensure consumers aren't broken and `yarn install` warning is no longer displayed.
- OS: macOS Sonoma 14.5
- `@graphql-codegen/typescript-react-apollo`: 4.3.0
- NodeJS: v20.11.1 …

fix(deps): move `graphql-tag` to devDeps from peerDeps for typescript-react-apollo

---

.changeset/smooth-timers-peel.md
packages/plugins/typescript/vue-urql/src/visitor.ts
packages/plugins/typescript/vue-urql/tests/__snapshots__/urql.spec.ts.snap
packages/plugins/typescript/vue-urql/tests/urql.spec.ts

Generation template for vue urql query/subscription was changed in https://github.com/dotansimha/graphql-code-generator-community/pull/329.
That was necessary due to [changes](https://github.com/urql-graphql/urql/pull/3022) in `urql-vue` lib, which caused a number of regressions. Currently, all of them was [fixed](https://github.com/urql-graphql/urql/pulls?q=is%3Apr+is%3Aclosed+vue) and finally [released](https://github.com/urql-graphql/urql/releases/tag/%40urql%2Fvue%401.4.0) with `urql-vue@1.4.0`
This PR basically reverts https://github.com/dotansimha/graphql-code-generator-community/pull/329 and and fits `urql-vue@1.4.0` changes.
Related #328
Related #403
Related https://github.com/dotansimha/graphql-code-generator/issues/9421
- Was built and used in live internal project
**Test …

fix(typescript-vue-urql): variable typing

---

.changeset/lazy-games-juggle.md
dev-test/githunt/types.reactApollo.customSuffix.tsx
dev-test/githunt/types.reactApollo.hooks.tsx
dev-test/githunt/types.reactApollo.preResolveTypes.tsx
dev-test/githunt/types.reactApollo.tsx
dev-test/githunt/types.reactApollo.v2.tsx
dev-test/star-wars/__generated__/HeroAndFriendsNames.tsx
dev-test/star-wars/__generated__/HeroAppearsIn.tsx
dev-test/star-wars/__generated__/HeroDetails.tsx
dev-test/star-wars/__generated__/HeroDetailsWithFragment.tsx
dev-test/star-wars/__generated__/HeroName.tsx
dev-test/star-wars/__generated__/HeroNameConditional.tsx
dev-test/star-wars/__generated__/HeroParentTypeDependentField.tsx
dev-test/star-wars/__generated__/HeroTypeDependentAliasedField.tsx
dev-test/star-wars/__generated__/HumanWithNullWeight.tsx
dev-test/star-wars/__generated__/TwoHeroes.tsx
dev-test/star-wars/types.refetchFn.tsx
dev-test/test-message/types.tsx
packages/plugins/typescript/react-apollo/src/visitor.ts
packages/plugins/typescript/react-apollo/tests/__snapshots__/react-apollo.spec.ts.snap
packages/plugins/typescript/react-apollo/tests/react-apollo.spec.ts

_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Support skip token for suspense query.
From https://www.apollographql.com/docs/react/api/react/hooks/#suspensequeryhookoptions-skip, it's mentioned that `skip` is deprecated in favor of `skipToken` for `useSuspenseQuery`:
> We recommend using skipToken in place of the skip option as it is more type-safe. This option is deprecated and only supported to ease the migration from useQuery. It will be removed in a future release.
Related #647
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and …

feat(typescript-react-apollo): support skip token for useSuspenseQuery

---

.changeset/clean-beers-bathe.md
packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts
packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts

This PR adds the data contract attributes for enum values to ensure the serialized strings are matching exactly what the schema expects. This is to support different value styles, per the linked issue.
Related # (issue)
#1161 
I updated the existing test case covering enums to include the attributes, and added a new value SHOUTY_SNAKE_VALUE.
I made a unit test on some C# code and verified that `Newtonsoft.Json` would accept `"value2"` as a string for the Value2 enum, however my example would not.
The enum as generated by this PR
- OS: Windows
- `@graphql-codegen/c-sharp-operations`: `3.1.1`
- NodeJS: 20.15.1
The PR #1160 I just created …

Add support for enum string values with data contract attributes

---

.changeset/light-actors-trade.md
.changeset/swift-pens-prove.md
packages/plugins/c-sharp/c-sharp-common/src/json-attributes.ts
packages/plugins/c-sharp/c-sharp-operations/src/visitor.ts
packages/plugins/c-sharp/c-sharp-operations/test/c-sharp-operations.spec.ts

This PR prevents duplicate classes being generated by using the property named of the GQL type name as the basis for class name generation.
This will result in different class names, but it solves this issue.
Related # (issue)
#901
expected)
This code is being used by us in production, where we have numerous fragments that was affected by the linked issue. I have updated the existing tests because it does change the name of the generated classes. 
Copilot helped update the tests, this was its summary of the changes.
Nested Response Classes have been changed from type-based naming to field-based naming:
PersonSelection → MeSelection (for the me field)
PersonSelection → YouSelection (for the you field)
Reserved Keyword Tests: Updated class names …

Prevent duplicate class generation by using the property name (instead of the GQL type name) as the basis for class name generation 
